name: "Auto Approve & Merge Dependabot PRs"

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-approve-merge:
    name: 'Auto Approve & Merge Dependabot PRs'
    uses: shopyos/github-workflows/.github/workflows/dependabot-approve-merge.yml@main
    secrets: inherit